version: '3.8'

services:
  db_zea:
    image: postgres:14
    container_name: postgres_db_zea
    env_file:
      - ../.env
    ports:
      - "5437:5432"
    volumes:
      - postgres_data_zea:/var/lib/postgresql/data
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_zea:
    image: redis:6
    container_name: redis_zea
    ports:
      - "6387:6379"
    networks:
      - portfolio_network

  web_zea:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_zea
    command: sh -c "/entrypoint.sh && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8082"
    volumes:
      - ../app:/app
      - ../app/static:/app/static
      - ../app/media:/app/media
      - ~/.ssh/zea_control_deploy:/root/.ssh/id_ed25519:ro
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - CELERY_STACK=zea
    depends_on:
      db_zea:
        condition: service_healthy
      redis_zea:
        condition: service_started
    ports:
      - "127.0.0.1:8089:8082"
    networks:
      - portfolio_network

  celery_worker_zea:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: celery_worker_zea
    command: celery -A core worker -l info
    volumes:
      - ../app:/app
      - ~/.ssh/zea_control_deploy:/root/.ssh/id_ed25519:ro
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - CELERY_STACK=zea
    depends_on:
      db_zea:
        condition: service_healthy
      redis_zea:
        condition: service_started
    networks:
      - portfolio_network

  celery_beat_zea:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: celery_beat_zea
    command: celery -A core beat -l info
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - CELERY_STACK=zea
    depends_on:
      db_zea:
        condition: service_healthy
      redis_zea:
        condition: service_started
    networks:
      - portfolio_network

  telegram_bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram_bot_zea
    command: python manage.py bot
    volumes:
      - ../app:/app       # исправлено
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - CELERY_STACK=zea
    depends_on:
      - db_zea
      - web_zea
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge

volumes:
  postgres_data_zea:
